version: '3.4'

services:
  ui:
    build:
      context: ./cicd/docker-local
    container_name: hf-ui
    environment:
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING:-true}
    ports:
      - '${UI_PORT:-16200}:4200'
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      # bind-mount files in root needed by npm
      - ./angular.json:/app/angular.json
      - ./browserslist:/app/browserslist
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./setup-local.js:/app/setup-local.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tslint.json:/app/tslint.json
      # bind-mount src directory
      - ./src:/app/src
      # volumes for npm cache and node_models
      - npm-cache:/home/node/.npm
      - node-modules-cache:/app/node_modules

volumes:
  npm-cache: {}
  node-modules-cache: {}
